### ISSUE TITLE
Feasibility

### ISSUE THREAD

**Issue by serkolch** [mgershowitz/purple-rain-game-yahtzee#1]
@mgershowitz 
Hey Matt,

The idea is definitely within the scope of what we've learned. There are a lot of moving pieces here, so it'll take a lot of planning beforehand to save yourself a lot of hassle later on. Definitely work with Cyrus to plan this out tonight. 

Before then, you can work on building out a basic layout based on your wireframe (it looks good!)

I like the background into Yahtzee, as it's definitely a more complicated game. It's not the same as user stories (which I see at the bottom). Could you please use a little Markdown styling (https://daringfireball.net/projects/markdown/syntax might help) to separate each action? Also, each user story should be a distinct action and not a combination of actions.

**Comment by mgershowitz** [comment]
Hey Sergey,

Awesome, I'll make sure to do some planning with Cyrus and then style the
readme and user stories a little better.

Thanks,

Matt
